# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_embed.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'audio_embed.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61udio_embed.proto\x12\naudioembed\"0\n\x0c\x45mbedRequest\x12\x0e\n\x06songId\x18\x01 \x01(\t\x12\x10\n\x08\x61udioUrl\x18\x02 \x01(\t\"2\n\rEmbedResponse\x12\x0e\n\x06songId\x18\x01 \x01(\t\x12\x11\n\tembedding\x18\x02 \x03(\x02\x32J\n\nAudioEmbed\x12<\n\x05\x45mbed\x12\x18.audioembed.EmbedRequest\x1a\x19.audioembed.EmbedResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_embed_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDREQUEST']._serialized_start=33
  _globals['_EMBEDREQUEST']._serialized_end=81
  _globals['_EMBEDRESPONSE']._serialized_start=83
  _globals['_EMBEDRESPONSE']._serialized_end=133
  _globals['_AUDIOEMBED']._serialized_start=135
  _globals['_AUDIOEMBED']._serialized_end=209
# @@protoc_insertion_point(module_scope)
